-- Extensions used by the project.
--
-- Supabase (local and hosted) already installs pgcrypto in the `extensions`
-- schema, so `create extension if not exists pgcrypto;` — without the
-- `with schema` — was a silent no-op that only *looked* like it guaranteed
-- something. Declaring the schema explicitly documents where the extension
-- actually lives and keeps the migration correct if it ever runs against a
-- database where it does not yet exist.
--
-- Correction to the old comment: `gen_random_uuid()` does NOT come from
-- pgcrypto on PG13+, it comes from `pg_catalog` (it is builtin). What the
-- project uses from pgcrypto is `digest()`, for document hashing.
--
-- WARNING — `digest()` lives in `extensions`, not in `public`. Any function
-- that pins search_path the way `public.rate_limit_hit` does
-- (`set search_path = pg_catalog, public`) must call it **fully qualified**, as
-- `extensions.digest(...)`; without that the resolver cannot find it and the
-- function breaks at runtime, not at deploy time.
-- Checked against the real database:
--   set search_path = pg_catalog, public;
--   select to_regprocedure('digest(bytea,text)');            -- NULL
--   select to_regprocedure('extensions.digest(text,text)');  -- resolves
create extension if not exists pgcrypto with schema extensions;
